meta:
  flow: Classic
  substituting_steps:
    Checker.DisconnectedPins: null

    # Promote power pins
    +Odb.ManualMacroPlacement: Odb.FABulousPower
    
    # TODO
    OpenROAD.IRDropReport: null
    Checker.YosysUnmappedCells: null

DESIGN_NAME: tt_um_fabulous_sky_26c
VERILOG_FILES:
  - dir::src/tt_um_fabulous_sky_26c.sv
  - dir::ip/fabric_config/fabric_config.sv
  - dir::ip/fabric_bitbang/fabric_bitbang.sv
  
CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

FP_SIZING: "absolute"
DIE_AREA: [0, 0, 1378.160, 511.360]
FP_DEF_TEMPLATE: dir::src/tt_block_8x4_pg.def

PDN_CFG: dir::src/pdn_cfg.tcl
#PDN_EXTEND_TO: "boundary"

PDN_VOFFSET: 8
PDN_VPITCH: 25
PDN_VWIDTH: 3.2

PL_TARGET_DENSITY_PCT: 44 #45
GRT_ALLOW_CONGESTION: true

# TODO enable clock gating?
#SYNTH_CLOCKGATE_POSEDGE_ICG: "sg13g2_lgcp_1/GATE/CLK/GCLK"
#SYNTH_CLOCKGATE_MIN_WIDTH: 4

RT_MAX_LAYER: met4
FP_PDN_MULTILAYER: False

# Width should be multiple of 0.46 (Metal2 pitch)
# Height should be multiple of 0.68 (Metal3 pitch)
# Standard cell row height: 2.72 (4 Metal3 tracks)
FP_MACRO_HORIZONTAL_HALO: expr::(0.46 * 8)
FP_MACRO_VERTICAL_HALO: expr::(0.68 * 4)

# Save some more core area
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 2

LEFT_MARGIN_MULT: 4
RIGHT_MARGIN_MULT: 1

FP_OBSTRUCTIONS:
- [expr::(0.46 * (2950)), 0, "expr::$DIE_AREA[2]", "expr::($DIE_AREA[3] - (0.68 * 72))"]

MACROS:
  tiny_fabric_10x4:
    gds:
      - dir::fabrics/tiny_fabric_10x4/macro/sky130A/gds/tiny_fabric_10x4.gds
    lef:
      - dir::fabrics/tiny_fabric_10x4/macro/sky130A/lef/tiny_fabric_10x4.lef
    nl:
      - dir::fabrics/tiny_fabric_10x4/macro/sky130A/nl/tiny_fabric_10x4.nl.v
    instances:
      tiny_fabric_10x4:
        location: [expr::((0.46 * 120)), expr::(0.68 * 1)] # expr::(0.68 * 27)
        orientation: FS

ERROR_ON_PDN_VIOLATIONS: False

PDN_MACRO_CONNECTIONS:
- "tiny_fabric_10x4 VPWR VGND VPWR VGND"

# No extract-unique, because the power straps
# are connected in the top-level integration
MAGIC_EXT_UNIQUE: notopports

# Tiny Tapeout expects pins to match the template DEF
MAGIC_WRITE_LEF_PINONLY: true
