name: CI

# Events that trigger the workflow
on:
  # Runs on all pushes to branches
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  tiles:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pdk: [sky130A]
        tile_library: [tiny]
    name: Tiles (${{ matrix.tile_library }}/${{ matrix.pdk }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
          derivation: github:mole99/librelane_plugin_fabulous
      - name: Cache the tiles
        uses: actions/cache@v5
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ matrix.tile_library }}-${{ matrix.pdk }}-${{ github.sha }}
      - name: Implement the tiles
        run: |
          PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ matrix.tile_library }} nix develop --command bash -c "cd ip/fabulous-tiles/ && make all"
      
  fabrics:
    runs-on: ubuntu-24.04
    needs: [tiles]
    strategy:
      matrix:
        pdk: [sky130A]
        fabrics: [tiny_fabric_10x4]
    name: Fabric (${{ matrix.fabrics }}/${{ matrix.pdk }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
          derivation: github:mole99/librelane_plugin_fabulous
      - name: Get the tile library
        run: |
          echo "TILE_LIBRARY=$(echo "${{ matrix.fabrics }}" | cut -d'_' -f1)" >> $GITHUB_ENV
      - name: Restore the tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Stitch the tiles
        run: |
          PDK=${{ matrix.pdk }} nix develop --command make ${{ matrix.fabrics }}
          make copy-fabric
      - name: Upload Macro Folder
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fabrics }}_${{ matrix.pdk }}
          path: fabrics/${{ matrix.fabrics }}/macro/${{ matrix.pdk }}/
          include-hidden-files: true
      - name: Build the User Designs
        run: |
          cd user_designs; PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command make all
      - name: Simulate the Fabric (Emulation)
        run: |
          EMULATION=counter PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command bash -c "cd tb; python3 fabric_tb.py"
      - name: Simulate the Fabric (Simulation)
        run: |
          PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command bash -c "cd tb; python3 fabric_tb.py"
      - name: Build TT FPGA
        run: |
          nix develop --command make tt-fabulous
          make copy-tt
      - name: Simulate the FPGA RTL (Emulation)
        run: |
          EMULATION=top_counter PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command bash -c "cd tb; python3 top_tb.py"
      - name: Simulate the FPGA RTL (Simulation)
        run: |
          PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command bash -c "cd tb; python3 top_tb.py"
      - name: Set up the PDK
        run: |
          nix develop --command ciel enable --pdk-family sky130 026824c7969ce6f4fc9678e6ca04b0a06a596c4b
      - name: Simulate the FPGA RTL/GL (Simulation)
        run: |
          GL=1 PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command bash -c "cd tb; python3 top_tb.py"
